### ISSUE TITLE
2020/01/01/my-iot-devices-en/

### ISSUE THREAD

**Issue by zcbenz** [japaniot/japaniot.github.io#2]
Blog images:

<img src="https://user-images.githubusercontent.com/639601/71551583-d8f43780-2a2d-11ea-8dbe-2bfa31ebe4d0.jpeg" width="200" height="141" />
<img src="https://user-images.githubusercontent.com/639601/71551298-67b18600-2a27-11ea-9a1b-3049371f7436.jpeg" width="400" height="303" />
<img src="https://user-images.githubusercontent.com/639601/71551299-67b18600-2a27-11ea-89ee-d89c22b57c3c.jpeg" width="300" height="223" />
<img src="https://user-images.githubusercontent.com/639601/71553048-80cc2e00-2a4b-11ea-84fd-b3f13f8869ba.png" width="200" height="394" />
<img src="https://user-images.githubusercontent.com/639601/71553056-aa855500-2a4b-11ea-836f-77f373165b38.png" width="451" height="200" />
<img src="https://user-images.githubusercontent.com/639601/71553458-2c2cb100-2a53-11ea-9396-b236f3905b30.jpeg" width="300" height="155" />
<img src="https://user-images.githubusercontent.com/639601/71553497-980f1980-2a53-11ea-91a9-a198959bb8f9.jpeg" width="600" height="254" />
<img src="https://user-images.githubusercontent.com/639601/71564007-802fa800-2adc-11ea-8ef8-d677f7bc501d.jpg" width="266" height="150" />
<img src="https://user-images.githubusercontent.com/639601/71564036-28de0780-2add-11ea-87f5-7d756250be31.jpg" width="300" height="226" />

**Comment by zcbenz** [comment]
测试

**Comment by chrismaurer** [comment]
Hello. Sorry to bother you, but I just wanted to send a greeting. I have never met anyone else working on a HomeKit home in Japan, so I was happy to find your site. Thanks to the information you posted, I am looking at the AdvanceSeries LinkModel switches and if I am able to use them in my home, I will probably use your Homebridge plugin. Thank you for posting this information! Yoroshiku onegaishimasu.

**Comment by hbkmanbass** [comment]
Hello, I’m happy to find someone who like iOT and use nature Remo in Japan. I’m thinking about making Nature Remo more smart but can’t find an issue. 
I would like to turn off my aircon when I open the window for 10 sec for example. What sensor will you use ? How will you link Nature Remo with other HK system ? 
Thanks in advance

**Comment by MichaelPils** [comment]
hello I read your entry with interest. I also own a Dyson 360 Heurist and have the plugin installed. But now I keep getting the following error message:

[DysonRobot] FetchError: invalid json response body at https://appapi.cp.dyson.com/v1/userregistration/authenticate?country=CH reason: Unexpected token < in JSON at position 0
    at /usr/local/lib/node_modules/homebridge-dyson-robot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getDevices (/usr/local/lib/node_modules/homebridge-dyson-robot/lib/dyson-link.js:17:23)
    at DysonRobot._init (/usr/local/lib/node_modules/homebridge-dyson-robot/lib/index.js:45:22) {
  type: 'invalid-json'
}

Do you have any idea what the problem could be?
Thanks for your help
